### ISSUE TITLE
[Wednesday] [Week 11] 5: Demo v1.3

### ISSUE THREAD

**Issue by Cloud7050** [AY2324S1-CS2103-W14-3/tp#129]
https://nus-cs2103-ay2324s1.github.io/website/schedule/week11/project.html#5-demo-v1-3-before-the-tutorial

If our #125 release is not yet ready, we could probably just use the current master.

Alternatively, we could make an early v1.3 release which we use for this demo. Then release another, say, v1.3.1 before Friday. The feature freeze should then apply to the latter.

**Comment by rayshawntan** [comment]
v1.3 demo is in https://docs.google.com/document/d/1IkD1rgbejQnlv7g2PEbDA_gM-wX81U1p4ZmLRBw8vIw/edit
