### ISSUE TITLE
[PE-D][Tester A] Would be good to show the various errors is possible

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-W14-3/tp#152]
![image.png](https://raw.githubusercontent.com/bhnuka/ped/main/files/35211091-2193-4c11-b17e-71be44da9546.png)

Currently, if there are multiple errors, you only list one. It would be good if you could find a way to accumulate the errors or add clarity to your message and state that more errors may be present.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bhnuka/ped#1

**Comment by Cloud7050** [comment]
Needs further discussion.

Due to feature freeze, we can only document this as a future enhancement.

**Comment by Cloud7050** [comment]
**Decision**

- Planned enhancement: Support for displaying multiple errors if a command has multiple problems.
  Probably low priority. If another enhancement needs the slot, we could omit this.

**Comment by Cloud7050** [comment]
Linking #96

**Comment by bwangpj** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/70694994/b7d37d12-baed-4f0d-b8a0-a9138d6641cf)

I don't think we can include this in planned enhancements, as it will require changing many features (it is too generic). I would say it is low priority anyway.

**Comment by Cloud7050** [comment]
Fair point. In that case, we may need to take a look at #155 again.

**Comment by Cloud7050** [comment]
Closing as per the above.
