### ISSUE TITLE
[PE-D][Tester A] Lack of example outcomes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-3/tp#156]
Your UG is a bit inconsistent when it comes to Examples and outcomes. For some commands (i.e Find) you have a fair few examples and outcomes under format. However, for examples such as filter, you state some example formats but no outcomes. This is hence another area where you could have more visuals or explanation to make it clearer for users.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: bhnuka/ped#3

**Comment by Cloud7050** [comment]
Outcomes are only provided for the more complex commands. For the outcomes for simpler commands, the generic descriptions/examples above the copy-pasteable example commands should suffice. We could look into this regardless.

**Comment by mamayuan** [comment]
I think we can add screenshots as quick illustration

**Comment by Cloud7050** [comment]
~~We elaborate for the examples of `edit` and `delete`, but I don't think we would then be required to also add elaborations to the rest of the example commands to achieve some form of consistency. The generic explanations and "e.g." examples above the example commands should provide enough detail.~~

I see what the tester means. Basically `filter` has less docs and "e.g." examples than `find`, and possibly in comparison to some of the other more complex commands. Though some of the simpler commands shouldn't need so much written about them.

@bwangpj perhaps consider writing up more stuff for `filter`? Or if not needed, can just close this issue.

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/29337685-c937-4504-a752-6bc86d31422c)
