### ISSUE TITLE
[PE-D][Tester A] Lack of examples (Delete)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-3/tp#159]
For your delete command, under format, you stated that if duplicate indices are entered, only one would be counted. I feel as though as this is a unique case, it should be highlighted under examples as well for greater clarity.

Do note that this is separate from the previous issue as this focuses on the omission of certain examples rather than outcomes.

![image.png](https://raw.githubusercontent.com/bhnuka/ped/main/files/e286147e-d29c-4554-8ada-eea5dc617f22.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: bhnuka/ped#4

**Comment by Cloud7050** [comment]
Could elaborate in docs.

Specifying the same index multiple times is a bit pointless and condensing them is more so for the user's convenience. Copy-pasteable examples are currently meant to be "good" examples, so we don't provide non-standard commands, such as for testing purposes. However, an added "e.g." style of line below the bullet point may fit for elaboration.
