### ISSUE TITLE
[PE-D][Tester B] Preceding white space allowed in edit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-W14-3/tp#160]
![image.png](https://raw.githubusercontent.com/nicholascher/ped/main/files/07f154a7-4a59-4890-b513-d07c23a95a35.png)

Users are allowed to have preceding whitespaces before the commands.

**Command Used**:             edit 1 n/ Ben Lee

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: nicholascher/ped#5

**Comment by bwangpj** [comment]
Is this a bug? :joy:

**Comment by Cloud7050** [comment]
AB3 parser trims such whitespace that is insignificant. I would consider it a feature that also makes things more convenient.
