### ISSUE TITLE
[PE-D][Tester B] Edit command does not check for duplicate tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-3/tp#163]
![image.png](https://raw.githubusercontent.com/nicholascher/ped/main/files/a44cb2bc-5928-48e2-b0b7-4aab6aacf052.png)

The edit command does not enforce the same check as the add command where duplicate tags where simply treated as the same tag.

**Command Used**: edit 5 t/          test 1             t/test1

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nicholascher/ped#6

**Comment by Cloud7050** [comment]
Looks like the tags shown are not duplicates due to the spacing.

We could investigate more regardless. See how adding and editing differs for handling those two tags. And see how each of them handles actually duplicate tags.

**Comment by Cloud7050** [comment]
**Rejected**

From testing, the edit command does act like the add command in that it automatically condenses truly duplicate tags.
