### ISSUE TITLE
[PE-D][Tester B] Non numeric characters allowed in the edit command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-3/tp#166]
![image.png](https://raw.githubusercontent.com/nicholascher/ped/main/files/c1271704-aa6b-4bc5-b084-cb66375db1f4.png)

The edit command does not enforce the check for non numeric characters in the phone number

**Command Used**: edit 5 p/123p/123

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nicholascher/ped#7

**Comment by Cloud7050** [comment]
Phone number just needs to start with 3 digits. May be able to make it even clearer in the docs.

This is to allow stuff like "98765432 (mobile)", for example (iirc). May be able to update the sample data, docs etc to show this.

May also edit regex to allow optional leading +. But would need to update docs accordingly. Unless this counts as a feature edit already.

**Comment by rayshawntan** [comment]
Upon checking through, the issue seems to be in `Phone.java` where the regex is currently `"^\\d{3,}.*$"`. This seems to result to the above bug to occur. A solution to this would be to revert back to the regex in AB3 which is `"^\\d{3,}"`.

**Comment by Cloud7050** [comment]
Phone is one of the examples the site gave under relaxing validation to allow users to be more flexible in the way they use the app. I don't think we should (plan to) go back to restricting to just digits.

**Comment by rayshawntan** [comment]
In that case, we should replace `.` with something else, in regex that seems to allow all characters instead which results in the bug above to occur.

**Comment by Cloud7050** [comment]
Do you have ideas for a more restrictive set of characters? I went with `.` for flexibility.

**Comment by Cloud7050** [comment]
Come to think of it, atm we just freely allow users to type something like "999 (police/emergency)", which would have a slash anyway. Tradeoff of restrictive validation vs allowing flexible inputs.

**Comment by rayshawntan** [comment]
> Come to think of it, atm we just freely allow users to type something like "999 (police/emergency)", which would have a slash anyway. Tradeoff of restrictive validation vs allowing flexible inputs.

I think this would defeat the purpose of having the other fields then. `Phone` should only contain the phone number, and not any other details.

**Comment by rayshawntan** [comment]
I think police/emergency is more suited to used as Tag instead

**Comment by Cloud7050** [comment]
Maybe that was a bad example off the top of my head. Now that I'm on desktop, the changes of #97 were influenced by this part of the website:

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/8033b621-1017-4ead-a612-3b8d20a2fb79)

What's a good way to proceed?

**Comment by bwangpj** [comment]
Yeah I was quite confused by that part of the website too - I personally think it is quite contradictory and not possible to satisfy all at the same time. I think the solution they are looking for is to show a warning for phone number with special characters, but still allow it to go through. However, I don't know if we are able to add warnings in v1.4.

**Comment by rayshawntan** [comment]
I think since we have `AlternateContact`, maybe we can add it in UG as a tip for user to make use of it to fill in extra contacts like office numbers?

**Comment by Cloud7050** [comment]
> I think since we have `AlternateContact`, maybe we can add it in UG as a tip for user to make use of it to fill in extra contacts like office numbers?

That could work, some example/recommended usage of the alternate contacts feature in the UG. That would also clarify what types of contacts it is designed to support.

**Comment by Cloud7050** [comment]
**Decision**

- As part of our planned enhancements about warnings, warn for non-standard phone numbers (basically values that are not `\+?\d{3,15}`. But otherwise, keep the relaxed regex to allow users to input more flexible values if they so choose
- Add examples to the UG about what sorts of details users could put in alternate contacts, maybe social media as well as phone numbers. This would make it clearer what it's designed to support as of v1.4

**Comment by Cloud7050** [comment]
Awaiting PR merge to make it easier to edit this in.
