### ISSUE TITLE
[PE-D][Tester A] Lack of an undo or prior precaution when deleting or clearing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-3/tp#168]
As the contact program has two destructive features (that of delete and clear), there would ideally be a function to undo these commands, should there have been a misinput. Minimally, it would have been good to seek confirmation from the user before carrying out the command (i.e if delete 1 but meant to type delete 11, no way to get the contact back)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: bhnuka/ped#9

**Comment by bwangpj** [comment]
Not a feature flaw, to be added to Planned Enhancements. Linking #96.

**Comment by Cloud7050** [comment]
**Rejected**

This feels like more of a new feature request.
