### ISSUE TITLE
[PE-D][Tester B] Same success message shown even when no contacts are present.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-3/tp#176]
![image.png](https://raw.githubusercontent.com/nicholascher/ped/main/files/d76f1369-2a6d-4481-bc0c-bbc941084112.png)

**Commad Used**: clear followed by list

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: nicholascher/ped#9

**Comment by bwangpj** [comment]
Is this a bug? :joy:

**Comment by Cloud7050** [comment]
It's probably ok.
