### ISSUE TITLE
UG raw formatting bug in filter description

### ISSUE THREAD

**Issue by Cloud7050** [AY2324S1-CS2103-W14-3/tp#198]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/7268301e-7f64-4246-bb64-3faf01215d7f)

**Comment by Cloud7050** [comment]
- The raw `pre` tags can be seen
- It looks like extra spaces were intended or something, but it doesn't show up in the docs. So the meaning may become unclear
- "Keyword" is mentioned, but this is more so `find` terminology. The word could be updated to "tag"

**Comment by Cloud7050** [comment]
@bwangpj I forgot to mention this in the meeting, but FYI

**Comment by bwangpj** [comment]
That's strange, it looks fine on intellij (the pre tags were used to get the spaces to show up), I'll take a look again

**Comment by Cloud7050** [comment]
The solution may be simpler. We could paste real non-breaking spaces between the backticks. A bit like this: https://github.com/Cloud7050/tp/commit/613b14091a349cf55b3fad88405e34da9cbd5b8d.
