### ISSUE TITLE
Meeting findings

### ISSUE THREAD

**Issue by Cloud7050** [AY2324S1-CS2103-W14-3/tp#222]

**Comment by Cloud7050** [comment]
- Are use cases finalised?
- Are testing instructions finalised?
- Are we doing effort appendix?

**Comment by Cloud7050** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/b8acaddb-0f39-4a9c-81b3-d9ec49435ca1)
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/b9b25978-3552-4de1-ada4-5a1f9ac534c9)
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/d59c549d-9baa-4a56-89bc-c2250e9cbaaf)

**Comment by rayshawntan** [comment]
Not sure if this is intended.

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/83902023/9e3038d8-a266-4983-90e7-e206b8aac240)

**Comment by bwangpj** [comment]
> Not sure if this is intended.
> 
> ![image](https://user-images.githubusercontent.com/83902023/282458628-9e3038d8-a266-4983-90e7-e206b8aac240.png)

If you mean the spacing, it's intended

**Comment by rayshawntan** [comment]
> > Not sure if this is intended.
> > ![image](https://user-images.githubusercontent.com/83902023/282458628-9e3038d8-a266-4983-90e7-e206b8aac240.png)
> 
> If you mean the spacing, it's intended

I meant the (and this tag only). e.g.

**Comment by mamayuan** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/f544fccb-07a7-478d-948f-12c922646db9)
"changes" and "makes"

**Comment by Cloud7050** [comment]
> I meant the (and this tag only). e.g.

We may need a `\` at the end of the line to put the second `e.g.` on a newline.

**Comment by Cloud7050** [comment]
Should we remove the window resize saving part under manual testing? Seems like an AB3 feature we didn't change.

**Comment by mamayuan** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/dbc5553a-ad5b-4b33-8d72-0f777895069e)
This is what our help toolbar looks like
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/3a627f64-25a4-456c-bdfc-4ea85ec6196f)
should we change it to Help -> Help F1 instead

**Comment by mamayuan** [comment]
> Should we remove the window resize saving part under manual testing? Seems like an AB3 feature we didn't change.

Yea true, I think it should be removed

**Comment by Cloud7050** [comment]
> ![image](https://user-images.githubusercontent.com/97677245/282460352-dbc5553a-ad5b-4b33-8d72-0f777895069e.png) This is what our help toolbar looks like ![image](https://user-images.githubusercontent.com/97677245/282460562-3a627f64-25a4-456c-bdfc-4ea85ec6196f.png) should we change it to Help -> Help F1 instead

I think it's ok to leave out the shortcut text.

**Comment by Cloud7050** [comment]
> ![image](https://user-images.githubusercontent.com/97677245/282461156-a84b141e-ce7b-40b8-9798-3b04acabbd16.png) shading of the index numbers looks a bit inconsistent

Let's put the example ones in code blocks too?

**Comment by Cloud7050** [comment]
> ![image](https://user-images.githubusercontent.com/97677245/282462357-5074d1e0-7f8f-4bc3-96f8-4eac9dc76e9f.png) Do we keep this "Refer to the [PlantUML Tutorial at se-edu/guides](https://se-education.org/guides/tutorials/plantUml.html) to learn how to create and edit diagrams." in our DG?

"Future devs" would need to know how to maintain the docs, so I think it's fine to leave in.

**Comment by mamayuan** [comment]
> > ![image](https://user-images.githubusercontent.com/97677245/282462357-5074d1e0-7f8f-4bc3-96f8-4eac9dc76e9f.png) Do we keep this "Refer to the [PlantUML Tutorial at se-edu/guides](https://se-education.org/guides/tutorials/plantUml.html) to learn how to create and edit diagrams." in our DG?
> 
> "Future devs" would need to know how to maintain the docs, so I think it's fine to leave in.

Make sense

**Comment by mamayuan** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/6023aca8-aef4-42a1-82ff-cbadf88bc62d)
The arrows that point to {abstract UiPart} look different from the arrows in the remaining diagram, is this a problem?

**Comment by mamayuan** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/7b520c0f-fdf3-4b56-80b4-3a88bb35bfc9)
the example is `execute("delete 1 3 5")`, not the outdated `execute("delete 1")`

**Comment by bwangpj** [comment]
> ![image](https://user-images.githubusercontent.com/97677245/282464185-6023aca8-aef4-42a1-82ff-cbadf88bc62d.png) The arrows that point to {abstract UiPart} look different from the arrows in the remaining diagram, is this a problem?

Different as in overlapping? I think cause there's too many arrows. Not sure how to make plantuml make them not overlap

**Comment by rayshawntan** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/83902023/eeef4d41-5ecc-4f2e-a34a-1ea929261f1b)

Link is invalid. Goes to an website that's on sale. http://www.mcdodesign.com/

**Comment by mamayuan** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/61aa1698-81bd-4dc1-81d7-161e58f7b17f)
should we add multiplicity of 1 for Name/Phone etc in this class diagram for model component?

**Comment by Cloud7050** [comment]
> Link is invalid. Goes to an website that's on sale. http://www.mcdodesign.com/

I did notice the link is dead but don't really know how else to attribute it. Can't find the named person.

**Comment by Cloud7050** [comment]
> I'll add a note below as limitation of plantuml

Does Ma Yuan mean the arrowheads being clear triangles?

**Comment by bwangpj** [comment]
> > I'll add a note below as limitation of plantuml
> 
> Does Ma Yuan mean the arrowheads being clear triangles?

It's not supposed to be clear triangles?

**Comment by mamayuan** [comment]
> > I'll add a note below as limitation of plantuml
> 
> Does Ma Yuan mean the arrowheads being clear triangles?

Yea they look different in the same diagram which is kinda strange

**Comment by Cloud7050** [comment]
> It's not supposed to be clear triangles?

I'm not sure about the significance of the differing arrowhead.

**Comment by bwangpj** [comment]
https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/chapters/uml.html#class-inheritance

**Comment by Cloud7050** [comment]
> https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/chapters/uml.html#class-inheritance

Oh right those are all UI parts. Thanks.

**Comment by bwangpj** [comment]
> ![image](https://user-images.githubusercontent.com/97677245/282466424-61aa1698-81bd-4dc1-81d7-161e58f7b17f.png) should we add multiplicity of 1 for Name/Phone etc in this class diagram for model component?

Ah, just realised `AlternatePlatform` is wrong

**Comment by mamayuan** [comment]
I am not an expert on seuqence diagrams, but are the circled parts ok?
first one: activation bar should extend in both directions vertically?
![e6f8c7b4122cf223185526adfcf979d](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/f965ceaa-0ba2-4c60-b0d2-263120bceef7)
seond one: is there supposed to be an activation bar under CommandBox?
![5965d11c448b7f8844e07e7d04ee0e0](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/5ec05b2b-5e9e-401c-9067-61d9bf810fd8)

**Comment by Cloud7050** [comment]
> > Link is invalid. Goes to an website that's on sale. http://www.mcdodesign.com/
> 
> I did notice the link is dead but don't really know how else to attribute it. Can't find the named person.

The site in more recent years, when it got archived, was giving 301 and 403 HTTP status codes. But this is so odd...

https://web.archive.org/web/20160703163444/http://www.mcdodesign.com/

**Comment by Cloud7050** [comment]
> I am not an expert on seuqence diagrams, but are the circled parts ok?

I saw that but was guessing this is one of the cases where we omit an activation bar for brevity. For the first one, omitting the innermost nested bar.

**Comment by bwangpj** [comment]
> > I am not an expert on seuqence diagrams, but are the circled parts ok?
> 
> I saw that but was guessing this is one of the cases where we omit an activation bar for brevity. For the first one, omitting the outermost nested bar.

Yeah
https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/chapters/uml.html#minimal-notation

**Comment by mamayuan** [comment]
> > > I am not an expert on seuqence diagrams, but are the circled parts ok?
> > 
> > 
> > I saw that but was guessing this is one of the cases where we omit an activation bar for brevity. For the first one, omitting the outermost nested bar.
> 
> Yeah https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/chapters/uml.html#minimal-notation

Ahh okkk thanks for the clarification, guys

**Comment by rayshawntan** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/83902023/3eff0208-0e47-483e-be12-08d86d5c9c8b)

I missed out a "Use case ends." after 2.

**Comment by rayshawntan** [comment]
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/83902023/0cbd3d43-f5f2-4b81-97e4-987e06c98067)

Same for here and the MSS on top of 1.

**Comment by bwangpj** [comment]
> ![image](https://user-images.githubusercontent.com/83902023/282470924-0cbd3d43-f5f2-4b81-97e4-987e06c98067.png)
> 
> Same for here and the MSS on top of 1.

which one is MSS on top of 1?

**Comment by rayshawntan** [comment]
> > ![image](https://user-images.githubusercontent.com/83902023/282470924-0cbd3d43-f5f2-4b81-97e4-987e06c98067.png)
> > Same for here and the MSS on top of 1.
> 
> which one is MSS on top of 1?

Should be

Use case ...

MSS

1. ...
2. ...
Use case ends.

**Comment by rayshawntan** [comment]
Also missing full stops on the extension for UC06 and UC07 for use case ends.

**Comment by mamayuan** [comment]
Only first word is capitalised in similar sections
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/763c00a4-a3ef-46fd-906a-77f6a29b2cc3)
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/f79b9f96-4976-4f53-bfc5-a7a7e967338d)

so I think the requirements should not be capitalised then
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/97677245/c33267dd-07c8-4c4d-9a7c-889c724fc5fe)

**Comment by Cloud7050** [comment]
> Only first word is capitalised in similar sections ![image](https://user-images.githubusercontent.com/97677245/282471989-763c00a4-a3ef-46fd-906a-77f6a29b2cc3.png) ![image](https://user-images.githubusercontent.com/97677245/282472277-f79b9f96-4976-4f53-bfc5-a7a7e967338d.png)
> 
> so I think the requirements should not be capitalised then ![image](https://user-images.githubusercontent.com/97677245/282472117-c33267dd-07c8-4c4d-9a7c-889c724fc5fe.png)

Yeah let's make it consistent. Lowercase R.

**Comment by Cloud7050** [comment]
I've checked through, looks like all the things we've identified up to this point have been addressed in #224 (and #223).
