### ISSUE TITLE
index.md is not updated to ConText

### ISSUE THREAD

**Issue by rayshawntan** [AY2324S1-CS2103-W14-3/tp#57]
Main page of our website is not updated to our project.
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/83902023/9173e485-e56d-462b-bec9-c4faae9ac591)

**Comment by Cloud7050** [comment]
Unsure why this didn't get autoclosed again. Maybe actions haven't finished running?

**Comment by Cloud7050** [comment]
That doesn't seem to be the cause. Hm. Closing manually.
