### ISSUE TITLE
Continue refining TestData

### ISSUE THREAD

**Issue by Cloud7050** [AY2324S1-CS2103-W14-3/tp#68]
We may be able to continue the effort of #27 in V1.2b by refining our test data, removing redundant or duplicate strings and reducing the overall number of "people" etc.

**Comment by Cloud7050** [comment]
@rayshawntan or others, do you have any thoughts on this? Just thinking about what we can do in V1.2b such that everyone has stuff for the week. Maybe you feel #63 was enough for now, or have other ideas?

**Comment by rayshawntan** [comment]
I think its possible to reduce the overall number of "people" since quite a number of them don't really have any significant impact to the test cases.

**Comment by Cloud7050** [comment]
> I think its possible to reduce the overall number of "people" since quite a number of them don't really have any significant impact to the test cases.

@rayshawntan Ok. Since we didn't really meet this week, do you want to pick this issue up?

**Comment by rayshawntan** [comment]
@Cloud7050 sure

**Comment by Cloud7050** [comment]
Help text for certain commands are currently still in their `command/` files. Eg `MESSAGE_USAGE` in `AddCommand.java`. These contain sample data that is visible in production - lots of arbitrary strings.

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/c2c894f7-cde9-4832-86cd-d87ae69534ac)

We could incorporate this into the refinement, maybe move them into `Messages` while importing data from `ProductionData` or something.

In the end, we could have the documentation use similar values for consistency.

**Comment by Cloud7050** [comment]
I have laid a bit of stuff out in #73.
