### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Cloud7050** [AY2324S1-CS2103-W14-3/tp#69]
V1.2 code changes are now complete. This has caused some parts of the starting AB3 documentation to now be outdated. Let's look for such discrepencies and update them accordingly. That way, they won't be reported as many bugs in the PE dry run.

This is a bit vague, so we may be able to split this into multiple, more specific issues once this has been investigated.

**Comment by rayshawntan** [comment]
Shifting this to milestone v1.3 as we need to update documentation next.

**Comment by Cloud7050** [comment]
See also #98.

**Comment by Cloud7050** [comment]
Once we have decided which user stories to implement in our meeting and have converted them to issues, it may be applicable to update the user stories' categorisation.

**Comment by bwangpj** [comment]
Developer guide (user stories) and user guide needs to be heavily updated as many parts have become outdated.

**Comment by Cloud7050** [comment]
> As part of this, as identified in #71, we can update the GitHub code links in the DG. They currently point to the seedu repo.

This is included in #110.

**Comment by Cloud7050** [comment]
#114 included some general updates.

**Comment by Cloud7050** [comment]
This has been implemented to some extent. The original idea was to start updating the docs "unofficially" back in v1.2. Now, we can instead refer to issues such as #130, #127, #96, #93, #92.
