### ISSUE TITLE
Update unsupported / coming later features

### ISSUE THREAD

**Issue by Cloud7050** [AY2324S1-CS2103-W14-3/tp#96]
By updating the UG to specify that any applicable things we notice are either unsupported or coming in a theoretical "future version", we may be able to deflect some peer-identified bugs to prevent them from affecting grading. Let's update this section in the UG accordingly.

There is also a seemingly similar appendix of the DG for "planned enhancements" that would also need updating.

**Feel free to pitch in any ideas that come to mind by commenting here.**

(Guidelines for determining bugs @ https://nus-cs2103-ay2324s1.github.io/website/schedule/week10/project.html.)

See also #93.

**Comment by Cloud7050** [comment]
DG appendix of planned enhancements seems to be for deflecting feature flaws after the feature freeze is in effect. It sounds like we get to say what we could plan to do, and have it count as having addressed the feature flaw, provided the description is detailed enough (otherwise the description itself could get reported as having a feature flaw). It has limitations imposed, such as the max number we can have (4x2=8).

UG could complement the above by mentioning unsupported things or things coming in a future version.

Both of these can help with grading.

**Comment by Cloud7050** [comment]
> Also, accommodating 'extreme' inputs (e.g., a person name with 1000 characters) can be considered a nice-to-have feature, to be added in a future version (i.e., lack of it is not a bug).

**Comment by Cloud7050** [comment]
A "known limitation" could be the handling of very long names or commands.

**Comment by bwangpj** [comment]
I think this can only be finalised at least after we get some feedback from the PE dry run tomorrow, so shifting this to v1.4.

**Comment by bwangpj** [comment]
Many issues raised in PE-D center around making error messages better. We are not allowed to change these as, from course website, 
> It will be considered a feature change (i.e., not allowed to do) if,
> the current behavior is not strictly 'incorrect' but 'can be better'.
> the current behavior inconveniences the user but there is a way to work around it.

We can consider including enhancement of error messages in Planned Enhancements.

**Comment by Cloud7050** [comment]
We only have 8 slots. Maybe we can combine similar ones into a big description if we really need. But we'll have to close some of these issues choosing not to document some enhancements.

**Comment by bwangpj** [comment]
Planned Enhancements can only be feature tweaks and not addition of new features (according to course website), so for those comments from PE-D that would clearly require addition of entirely new features, we can safely close them.

**Comment by bwangpj** [comment]
I'll collate all and collate the similar ones, then we reduce to 8 from there.

**Comment by Cloud7050** [comment]
- More specific warnings
- Add warning messages like indices, duplicate tags/alternates
- Limiting phone numbers (regex)
- Alternate contact to support whitespace and symbols

**Comment by Cloud7050** [comment]
See also: https://github.com/AY2324S1-CS2103-W14-3/tp/pull/191#pullrequestreview-1722378457
