### ISSUE TITLE
[Week 10] 5: Smoke-test CATcher

### ISSUE THREAD

**Issue by Cloud7050** [AY2324S1-CS2103-W14-3/tp#99]
https://nus-cs2103-ay2324s1.github.io/website/schedule/week10/project.html#5-smoke-test-catcher-compulsory-counted-for-participation

---

- [x] @bwangpj
- [x] @Cloud7050
- [x] @mamayuan
- [x] @rayshawntan

**Comment by mamayuan** [comment]
Issue closed since all four of us have completed this
